projects:
  "zowe/perf-timing":
    unit:
      junit-artifact: perf-timing.yml/ubuntu-latest-18.x-results/unit/junit
      lcov-artifact: perf-timing.yml/ubuntu-latest-18.x-results/unit/coverage
  "zowe/imperative":
    unit:
      junit-artifact: imperative.yml/ubuntu-latest-18.x-results/unit/junit
      lcov-artifact: imperative.yml/ubuntu-latest-18.x-results/unit/coverage
    integration:
      junit-artifact: imperative.yml/ubuntu-latest-18.x-results/integration/junit
    system:
      test-count: npm-jest
  "zowe/zowe-cli":
    unit:
      junit-artifact: zowe-cli.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli.yml/ubuntu-latest-18.x-results/unit/coverage
    integration:
      junit-artifact: zowe-cli.yml/ubuntu-latest-18.x-results/integration
    system:
      test-count: npm-jest
  "zowe/zowe-cli-cics-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/zowe-cli-db2-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/zowe-cli-ftp-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/zowe-cli-ims-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    integration:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/integration
    system:
      test-count: npm-jest
  "zowe/zowe-cli-mq-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    integration:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/integration
    system:
      test-count: npm-jest
  "zowe/zowe-cli-scs-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-18.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/vscode-extension-for-zowe":
    unit:
      junit-artifact: zowe-explorer-ci.yml/zowe-explorer-results/unit
      lcov-artifact: zowe-explorer-ci.yml/zowe-explorer-results/unit/coverage
    unit-ftp:
      # junit-artifact: zowe-explorer-ftp-ci.yml/zowe-explorer-ftp-extension-results/unit
      lcov-artifact: zowe-explorer-ftp-ci.yml/zowe-explorer-ftp-extension-results/unit/coverage
