name: Zowe CLI Bundle All

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/zowe-cli-deploy-*.yaml'
      - 'scripts/deploy-*.js'
  schedule:
  - cron: '0 0 * * *'

jobs:
  build-v1-lts:
    uses: ./.github/workflows/zowe-cli-bundle.yaml
    with:
      dry-run: ${{ github.event_name != 'schedule' }}
      package-tag: zowe-v1-lts
      release-type: snapshot
  
  # build-v2-lts:
  #   uses: ./.github/workflows/zowe-cli-bundle.yaml
  #   with:
  #     dry-run: ${{ github.event_name != 'schedule' }}
  #     package-tag: zowe-v2-lts
  #     release-type: snapshot

  # build-next:
  #   uses: ./.github/workflows/zowe-cli-bundle.yaml
  #   with:
  #     dry-run: ${{ github.event_name != 'schedule' }}
  #     package-tag: next
  #     release-type: snapshot

  notify:
    runs-on: ubuntu-latest
    # needs: [build-v1-lts, build-v2-lts]
    needs: [build-v1-lts]
    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Generate Summary
      # run: node scripts/generate-summary.js ${{ needs.build-v1-lts.outputs.artifacts }} ${{ needs.build-v2-lts.outputs.artifacts }}
      run: node scripts/generate-summary.js ${{ needs.build-v1-lts.outputs.artifacts }}

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: summary.md
