name: Zowe CLI Deploy Component

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    inputs:
      pkg-name:
        description: "Name of the package to be deployed (the @zowe scope will be prepended)"
        default: "cli"
        required: true
      pkg-tag:
        description: "Tag to be distributed from Artifactory"
        default: "daily"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PKG_NAME: ${{ github.event.client_payload.pkgName || github.event.inputs.pkg-name }}
      PKG_TAG: ${{ github.event.client_payload.pkgTag || github.event.inputs.pkg-tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Deploy Package
      id: deploy
      run: node scripts/deploy-component.js ${{ env.PKG_NAME }} ${{ env.PKG_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLIC_TOKEN }}

    - name: Create Issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        ERROR_DETAILS: ${{ steps.deploy.outputs.error }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      with:
        filename: issue-template.md
        update_existing: true
