name: Zowe CLI Deploy All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.matrix.outputs.deploy-matrix }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Get Package Matrix
      id: matrix
      run: node scripts/get-package-matrix.js

  dispatch:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package: ${{ fromJson(needs.build.outputs.deploy-matrix) }}

    steps:
    - name: Set Environment Variables
      run: |
        IFS=":" | read -r PKG_NAME PKG_TAG <<< "${{ matrix.package }}"
        echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_ENV
        echo "PKG_TAG=${PKG_TAG}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Deploy Package
      id: deploy
      run: node scripts/deploy-component.js ${{ env.PKG_NAME }} ${{ env.PKG_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUBLIC_TOKEN }}

    - name: Create Issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        ERROR_DETAILS: ${{ steps.deploy.outputs.error }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      with:
        filename: issue-template.md
        update_existing: true
