name: Zowe CLI Deploy All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.matrix.outputs.deploy-matrix }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Get Package Matrix
      id: matrix
      run: node scripts/get-package-matrix.js

  dispatch:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package: ${{ fromJson(needs.build.outputs.deploy-matrix) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Set Environment Variables
      run: |
        IFS=":" | read -r PKG_NAME PKG_TAG <<< "${{ matrix.package }}"
        echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_ENV
        echo "PKG_TAG=${PKG_TAG}" >> $GITHUB_ENV

    - name: Deploy Component
      uses: zowe/zowe-cli-standalone-package/.github/workflows/zowe-cli-deploy-component.yaml@master
      with:
        pkg-name: ${{ env.PKG_NAME }}
        pkg-tag: ${{ env.PKG_TAG }}
