name: Zowe CLI Coverage

on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - run: npm ci

    - run: |
        node scripts/coverage-report.js
        npx csv2md coverage-report.csv >> $GITHUB_STEP_SUMMARY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        path: 'coverage-report.csv'
